sed -i 's/A/aa/g' ang1.1.txt
sed -i 's/I/ii/g' ang1.1.txt
sed -i 's/U/uu/g' ang1.1.txt
sed -i 's/G/~N/g' ang1.1.txt
sed -i 's/ch/Ch/g' ang1.1.txt
sed -i 's/c/ch/g' ang1.1.txt
sed -i 's/J/~n/g' ang1.1.txt
sed -i 's/z/sh/g' ang1.1.txt
sed -i 's/S/Sh/g' ang1.1.txt
